openapi: "3.0.0"

info:
  title: "Albrecht Drais WebAPI"
  description: "[Albrecht Drais] WebAPI Document"
  version: "1.0"

servers:
  - url: http://localhost:8080
    description: dev
  - url: https://api.server.test
    description: stg-tng
  - url: https://api.server.test
    description: stg-nks
  - url: https://api.server.test
    description: prod

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/v1/public/sandbox:
    $ref: "./paths/sandbox.yml"
  /api/v1/public/login:
    $ref: "./paths/login.yml"
  /api/v1/public/refresh-token:
    $ref: "./paths/refresh-token.yml"
  /api/v1/public/temporary-password:
    $ref: "./paths/temporary-password.yml"
  /api/v1/public/forgot-password:
    $ref: "./paths/forgot-password.yml"
  /api/v1/public/reset-password:
    $ref: "./paths/reset-password.yml"
  /api/v1/protected/change-password:
    $ref: "./paths/change-password.yml"
  /api/v1/protected/logout:
    $ref: "./paths/logout.yml"
  /api/v1/protected/staff:
    $ref: "./paths/staff.yml"
