openapi: "3.0.0"

info:
  title: "guppy-server application"
  description: "[guppy-server] WebAPIドキュメント"
  version: "1.0"

servers:
  - url: http://localhost:8080
    description: dev
  - url: https://api.server.test
    description: stg-tng
  - url: https://api.server.test
    description: stg-nks
  - url: https://api.server.test
    description: prod

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/v1/sandbox:
    $ref: "./paths/sandbox.yml"