spring:
  profiles:
    active: dev
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-database.yml

# for dev / ut
---
spring:
  config:
    activate:
      on-profile:
        - dev
        - ut

cors:
  allow-origins:
    - http://127.0.0.1:3000
    - http://localhost:3000
