spring:
  profiles:
    active: dev
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-database.yml
  # mvc:
  #   pathmatch:
  #     matching-strategy: ant_path_matcher

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# springdoc:
#   api-docs:
#     enabled: false
#   swagger-ui:
#     enabled: false
