name: build api

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_NAME: aldra_dev
      DB_USER: app
      DB_PASSWORD: BX3R7blD2UiPiM9F
      DB_JDBC_DRIVER: org.postgresql.Driver
      DB_JDBC_URL: jdbc:postgresql://127.0.0.1:5432/aldra_dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
      - name: Run Docker Containers
        run: docker-compose up -d --build
      - name: Run Flyway Migrate
        run: ./gradlew :aldra-database:flywayMigrate
      - name: Run OpenAPI Generator
        run: ./gradlew :aldra-api:oaGenerate
      - name: Run MyBatis Generator
        run: ./gradlew :aldra-database:mbGenerate
      - name: Run Spotless
        run: ./gradlew spotlessApply
      - name: Build aldra-api
        run: ./gradlew :aldra-api:build
