name: build api

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.7
      - name: OpenAPI Generator
        run: ./gradlew :aldra-api:oaGenerate
      - name: MyBatis Generator
        run: ./gradlew :aldra-database:mbGenerate
