name: build api

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Run Docker Containers
        run: docker-compose up -d
      - name: Run OpenAPI Generator
        run: ./gradlew :aldra-api:oaGenerate
      - name: Run MyBatis Generator
        run: ./gradlew :aldra-database:mbGenerate
